services:
  - type: worker
    name: reddit-nsfw-bot
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /
    healthCheckTimeout: 100
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
